# 🐼 Pandas - Class 4: Data Selection & Filtering
Welcome to **Class 4** of our Pandas series. Today we’ll explore techniques to select and filter data in a DataFrame.

## 1. Boolean Indexing & Conditional Selection
- Use comparison operators to build conditions (e.g., `df['col'] > 50`).
- Pass the condition inside `df[...]` to get matching rows.
- Combine multiple conditions with `&` (AND), `|` (OR), and `~` (NOT).
- Parentheses are required when combining conditions.

In [6]:
import numpy as np
import pandas as pd
a = {
    'Name':['Alice','Bob','Charlie','David','Emma'],
    'Age':[25, 30, 35, 40, 22],
    'Score':[88, 92, 79, 85, 95]
}
b = pd.DataFrame(a)

In [7]:
b

      Name  Age  Score
0    Alice   25     88
1      Bob   30     92
2  Charlie   35     79
3    David   40     85
4     Emma   22     95

In [8]:
b[b['Age']>30]

      Name  Age  Score
2  Charlie   35     79
3    David   40     85

In [12]:
b[(b['Age']>=30) & (b['Score']>80)]

    Name  Age  Score
1    Bob   30     92
3  David   40     85

In [14]:
b[(b['Age']>=30) | (b['Score']>90)]

      Name  Age  Score
1      Bob   30     92
2  Charlie   35     79
3    David   40     85
4     Emma   22     95

In [15]:
b[~(b['Score']>90)]

      Name  Age  Score
0    Alice   25     88
2  Charlie   35     79
3    David   40     85

## 2. Filtering Rows with Multiple Conditions
- Combine two or more conditions to refine selection.
- Remember to enclose each condition in parentheses.

In [16]:
b[(b['Age']>=30) & (b['Score']>80)]

    Name  Age  Score
1    Bob   30     92
3  David   40     85

## 3. Using `query()` for Cleaner Filtering
- `query()` allows filtering rows with a string expression.
- It's concise and readable for complex conditions.
- Variables can be passed using the `@` symbol.

In [17]:
b.query("Age>30")

      Name  Age  Score
2  Charlie   35     79
3    David   40     85

In [18]:
b.query("Age < 30 and Score > 80")

    Name  Age  Score
0  Alice   25     88
4   Emma   22     95

In [20]:
hold = 90
b.query("Score > @hold")

   Name  Age  Score
1   Bob   30     92
4  Emma   22     95

## 4. String Operations on Columns
- Use the `.str` accessor for vectorized string methods.
- Common methods: `contains`, `replace`, `startswith`, `endswith`, `lower`, `upper`.
- Useful for cleaning or filtering text data.

In [23]:
b['Name'].str.upper()

0      ALICE
1        BOB
2    CHARLIE
3      DAVID
4       EMMA
Name: Name, dtype: object

In [25]:
b['Name'].str.contains('a', case = False) # search the name which contain the 'a' or 'A' letter

0     True
1    False
2     True
3     True
4     True
Name: Name, dtype: bool

## Mini Practice
1. Build a DataFrame with columns such as Name, Age, City, Score.
2. Use boolean indexing to select rows where Age > 25.
3. Filter rows where City is either 'Delhi' or 'Mumbai'.
4. Use query() to find rows with Score >= 85 and Age < 35.
5. Clean a text column using str.replace or str.lower.

In [27]:


# 1. Build a DataFrame with columns: Name, Age, City, Score
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Emma', 'Frank'],
    'Age': [24, 32, 28, 40, 22, 30],
    'City': ['Delhi', 'Mumbai', 'Pune', 'Chennai', 'Delhi', 'Mumbai'],
    'Score': [90, 82, 88, 75, 95, 84]
}

df = pd.DataFrame(data)



# 2. Use boolean indexing to select rows where Age > 25
# Write your code here

# 3. Filter rows where City is either 'Delhi' or 'Mumbai'
# Write your code here

# 4. Use query() to find rows with Score >= 85 and Age < 35
# Write your code here

# 5. Clean a text column using str.replace or str.lower
# Example: convert City names to lowercase or replace "delhi" with "New Delhi"
# Write your code here

In [28]:
df[df['Age']>25]

      Name  Age     City  Score
1      Bob   32   Mumbai     82
2  Charlie   28     Pune     88
3    David   40  Chennai     75
5    Frank   30   Mumbai     84

In [29]:
df[(df['City']=='Delhi') | (df['City']=='Mumbai')]

    Name  Age    City  Score
0  Alice   24   Delhi     90
1    Bob   32  Mumbai     82
4   Emma   22   Delhi     95
5  Frank   30  Mumbai     84

In [30]:
df.query("Score >= 85 and Age < 35")

      Name  Age   City  Score
0    Alice   24  Delhi     90
2  Charlie   28   Pune     88
4     Emma   22  Delhi     95

In [31]:
df['City'].str.replace("Delhi", "New Delhi")

0    New Delhi
1       Mumbai
2         Pune
3      Chennai
4    New Delhi
5       Mumbai
Name: City, dtype: object

In [32]:
df['City'].str.lower()

0      delhi
1     mumbai
2       pune
3    chennai
4      delhi
5     mumbai
Name: City, dtype: object

---
## Summary
- Learned to use boolean indexing and conditional selection.
- Filtered rows with multiple conditions.
- Used `query()` for clean filtering.
- Applied string operations with the `.str` accessor.