# 🐼 Pandas - Class 1: Introduction & Setup
Welcome to your first class on **Pandas**. In this session, we'll learn what Pandas is, why we use it, and how to get started with Series and DataFrames.

## 1 What is Pandas and Why Use It?
Pandas is a powerful **Python library** for data analysis and manipulation.

Key points:
- Provides two main data structures: **Series** (1D) and **DataFrame** (2D).
- Makes working with tabular data easy and fast.
- Ideal for cleaning, transforming, and analyzing datasets.
- Works well with other libraries like NumPy, Matplotlib, and Scikit-Learn.

## 2 Installing & Importing Pandas
To install pandas, open your terminal or command prompt and run:
```bash
pip install pandas
```
Then, you can import it in Python as follows:

In [ ]:
import numpy as np
import pandas as pd

## 3 Understanding Series & DataFrame
- **Series**: One-dimensional labeled array, like a column in Excel.
- **DataFrame**: Two-dimensional table, similar to an Excel sheet or SQL table.

### Creating a Series from Python Lists or Dictionaries

In [ ]:
a = [1, 7, 2]
s = pd.Series(a, name = 'Roll No')


d ={"Shivam": 89,"Vikas":91,"Vikalp":96,"Rishabh":99}
pd.Series(d, name="Marks")

Shivam     89
Vikas      91
Vikalp     96
Rishabh    99
Name: Marks, dtype: int64

### Creating a DataFrame

In [ ]:
a ={
    "Name": ["Shivam","Vikas","Vikalp","Rishabh"],
    "Marks": [89,91,96,99],
    "Subject":["Math","English","Hindi","Biology"]
}
pd.DataFrame(a)

      Name  Marks  Subject
0   Shivam     89     Math
1    Vikas     91  English
2   Vikalp     96    Hindi
3  Rishabh     99  Biology

### Creating DataFrame from NumPy Arrays

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
pd.DataFrame(a, columns=['A', 'B', 'C'])

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

### Reading CSV / Excel Files (Sneak Peek)
You can read external data using:
```python
pd.read_csv('file.csv')
```
```python
pd.read_excel('file.xlsx')
```
We will explore this in detail later.

---
**Summary**
- Pandas is a must-know library for data analysis.
- We learned about Series & DataFrames.
- We saw how to create them from lists, dictionaries, NumPy arrays, and got a sneak peek at CSV/Excel files.