# 🐼 Pandas - Class 3: Data Cleaning Essentials
Welcome to **Class 3** of our Pandas series. Today we’ll learn how to clean and prepare data for analysis.

## Handling Missing Values
Real-world datasets often have missing data. Pandas offers:
- `isna()` / `isnull()` → detect missing values (returns True/False)
- `dropna()` → remove missing values (rows/columns)
- `fillna()` → replace missing values with a given value or method (e.g., forward fill)

Always inspect how much data is missing before deciding to drop or fill.

In [50]:
import pandas as pd
import numpy as np
a = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Age": [25, None, 35, 40, None],
    "City": ["Delhi", "Mumbai", None, "Bangalore", "Chennai"],
    "Score": [85, 91, np.nan, 88, 95]
}

b = pd.DataFrame(a)
b

      Name   Age       City  Score
0    Alice  25.0      Delhi   85.0
1      Bob   NaN     Mumbai   91.0
2  Charlie  35.0       None    NaN
3    David  40.0  Bangalore   88.0
4     Emma   NaN    Chennai   95.0

In [51]:
b.isnull().sum()

Name     0
Age      2
City     1
Score    1
dtype: int64

In [52]:
b['Age'] = b['Age'].fillna(b['Age'].mean())
b['Score'] = b['Score'].fillna(b['Score'].mean())
b['City'] = b['City'].fillna(b['City'].mode())

In [53]:
b

      Name        Age       City  Score
0    Alice  25.000000      Delhi  85.00
1      Bob  33.333333     Mumbai  91.00
2  Charlie  35.000000      Delhi  89.75
3    David  40.000000  Bangalore  88.00
4     Emma  33.333333    Chennai  95.00

## Changing Data Types (`astype`)
- Convert a column to a different type using `astype()`.
- Examples: converting strings to numbers, integers to floats, or columns to category.

Be careful: make sure the data is compatible with the new type!

In [54]:
a = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Age": [25, 30, 35, 40, 22],
    "Score": [88, 92, 79, 85, 95]
}

b = pd.DataFrame(a)

In [55]:
b['Score'] = b['Score'].astype(float)
b

      Name  Age  Score
0    Alice   25   88.0
1      Bob   30   92.0
2  Charlie   35   79.0
3    David   40   85.0
4     Emma   22   95.0

In [56]:
b.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     5 non-null      int64
 2   Score   5 non-null      float64
dtypes: float64(1), int64(1), object(1)
memory usage: 252.0+ bytes

## Replacing Values (`replace`)
- Use `replace()` to substitute specific values or patterns.
- Useful for cleaning labels, fixing typos, or mapping categories.

In [57]:
c = b.copy()

In [58]:
c

      Name  Age  Score
0    Alice   25   88.0
1      Bob   30   92.0
2  Charlie   35   79.0
3    David   40   85.0
4     Emma   22   95.0

In [59]:
c['Name'] = c['Name'].replace('Bob','Shivam')
c['Score'] = c['Score'].replace({88.0:90.0,95.0:97.0})
c

      Name  Age  Score
0    Alice   25   90.0
1   Shivam   30   92.0
2  Charlie   35   79.0
3    David   40   85.0
4     Emma   22   97.0

## Dropping Rows & Columns (`drop`)
- `drop(labels, axis=0)` → drop rows by index labels.
- `drop(labels, axis=1)` → drop columns by name.
- Use `inplace=True` if you want to modify the DataFrame directly.

In [60]:
c

      Name  Age  Score
0    Alice   25   90.0
1   Shivam   30   92.0
2  Charlie   35   79.0
3    David   40   85.0
4     Emma   22   97.0

In [61]:
c.drop([0,2], axis = 0)

     Name  Age  Score
1  Shivam   30   92.0
3   David   40   85.0
4    Emma   22   97.0

In [62]:
c.drop(['Age'], axis = 1)

      Name  Score
0    Alice   90.0
1   Shivam   92.0
2  Charlie   79.0
3    David   85.0
4     Emma   97.0

## Detecting & Removing Duplicates
- `duplicated()` → returns a Boolean Series marking duplicate rows.
- `drop_duplicates()` → remove duplicate rows.
- You can specify `subset` (columns) and `keep` ('first', 'last', or False).

In [63]:
data = {
    "Name": ["Alice", "Bob", "Charlie", "Alice", "Bob", "David"],
    "Age": [25, 30, 35, 25, 30, 40],
    "Score": [88, 92, 79, 88, 92, 85]
}

df = pd.DataFrame(data)

In [64]:
df.duplicated()

0    False
1    False
2    False
3     True
4     True
5    False
dtype: bool

In [65]:
df.drop_duplicates(inplace=True)
df

      Name  Age  Score
0    Alice   25     88
1      Bob   30     92
2  Charlie   35     79
5    David   40     85

## Mini Practice
1. Create a messy DataFrame with missing values, wrong data types, typos, extra columns, and duplicates.
2. Clean it step-by-step using what you learned:
   - Handle missing values
   - Change data types
   - Replace incorrect values
   - Drop unnecessary rows/columns
   - Remove duplicates

In [80]:
import pandas as pd
import numpy as np

# 1. Create a messy DataFrame
data = {
    "Name": ["Alice", "Bob", "Chrlie", "David", "Alice", None],
    "Age": ["25", "30", None, "40", "25", "30"],      # ages stored as strings, with missing value
    "City": ["Delhi", "Mumbai", "Pun", "Bangalore", "Delhi", "Mumbai"],  # typo: "Pun" -> "Pune"
    "Score": [85, None, 78, 88, 85, 91],              # missing value in Score
    "Extra": ["x", "y", "z", "x", "y", "z"]           # extra column we don't really need
}

df = pd.DataFrame(data)

print("Original messy DataFrame:")
print(df)

# 2. Handle missing values
# Fill or drop as needed

# 3. Change data types
# Convert Age to int, Score to float, etc.

# 4. Replace incorrect values
# Fix 'Pun' -> 'Pune', maybe unify Name spellings if needed

# 5. Drop unnecessary rows/columns
# Remove 'Extra' or any row you don't want

# 6. Remove duplicates
# Use duplicated() and drop_duplicates()

# 7. Final clean DataFrame
# Print the cleaned DataFrame and check info()

Original messy DataFrame:
     Name   Age       City  Score Extra
0   Alice    25      Delhi   85.0     x
1     Bob    30     Mumbai    NaN     y
2  Chrlie  None        Pun   78.0     z
3   David    40  Bangalore   88.0     x
4   Alice    25      Delhi   85.0     y
5    None    30     Mumbai   91.0     z

In [82]:
df['Name'] = df['Name'].fillna('Shivam')
df['Age'] = df['Age'].fillna('35')
df['Score'] = df['Score'].fillna(df['Score'].median())

In [86]:
df['Age'].astype(int)
df['Score'].astype(float)
df

     Name Age       City  Score Extra
0   Alice  25      Delhi   85.0     x
1     Bob  30     Mumbai   85.0     y
2  Chrlie  35        Pun   78.0     z
3   David  40  Bangalore   88.0     x
4   Alice  25      Delhi   85.0     y
5  Shivam  30     Mumbai   91.0     z

In [88]:
df['City'].replace({'Pun':'Pune'}, inplace = True)
df

     Name Age       City  Score Extra
0   Alice  25      Delhi   85.0     x
1     Bob  30     Mumbai   85.0     y
2  Chrlie  35       Pune   78.0     z
3   David  40  Bangalore   88.0     x
4   Alice  25      Delhi   85.0     y
5  Shivam  30     Mumbai   91.0     z

In [89]:
df.drop('Extra', axis = 1, inplace = True)

In [91]:
df.duplicated()
df.drop_duplicates(inplace = True)
df

     Name Age       City  Score
0   Alice  25      Delhi   85.0
1     Bob  30     Mumbai   85.0
2  Chrlie  35       Pune   78.0
3   David  40  Bangalore   88.0
5  Shivam  30     Mumbai   91.0

In [92]:
print(df)

     Name Age       City  Score
0   Alice  25      Delhi   85.0
1     Bob  30     Mumbai   85.0
2  Chrlie  35       Pune   78.0
3   David  40  Bangalore   88.0
5  Shivam  30     Mumbai   91.0

---
## Summary
- Learned to handle missing values (`isna`, `dropna`, `fillna`).
- Converted column data types with `astype`.
- Cleaned up incorrect entries with `replace`.
- Removed unwanted rows/columns with `drop`.
- Detected and removed duplicates.