# 🐼 Pandas - Class 7: Merging, Joining & Concatenation
Welcome to **Class 7** of our Pandas series. Today we’ll learn how to combine multiple DataFrames using different techniques.

## 1. Using `concat()` for Stacking Data
- `pd.concat()` combines DataFrames vertically (rows) or horizontally (columns).
- Use `axis=0` for vertical stacking (default), `axis=1` for horizontal.
- `ignore_index=True` can reset the index after concatenation.

In [15]:
import pandas as pd

# Dataset 1: Product details
df1 = pd.DataFrame({
    "ProductID": [101, 102, 103],
    "ProductName": ["Pen", "Notebook", "Marker"],
    "Price": [10, 50, 30]
})

# Dataset 2: More products (same columns as df1)
df2 = pd.DataFrame({
    "ProductID": [104, 105],
    "ProductName": ["Pencil", "Eraser"],
    "Price": [5, 8]
})

# Dataset 3: Additional info (different columns)
df3 = pd.DataFrame({
    "Stock": [100, 60, 80],
    "Rating": [4.5, 4.7, 4.8]
})

In [16]:
pd.concat([df1, df2], axis=0, ignore_index=True)

   ProductID ProductName  Price
0        101         Pen     10
1        102    Notebook     50
2        103      Marker     30
3        104      Pencil      5
4        105      Eraser      8

In [17]:
pd.concat([df1,df3])

   ProductID ProductName  Price  Stock  Rating
0      101.0         Pen   10.0    NaN     NaN
1      102.0    Notebook   50.0    NaN     NaN
2      103.0      Marker   30.0    NaN     NaN
0        NaN         NaN    NaN  100.0     4.5
1        NaN         NaN    NaN   60.0     4.7
2        NaN         NaN    NaN   80.0     4.8

In [18]:
pd.concat([df1,df3], axis = 1, ignore_index = False)

   ProductID ProductName  Price  Stock  Rating
0        101         Pen     10    100     4.5
1        102    Notebook     50     60     4.7
2        103      Marker     30     80     4.8

## 2. Using `merge()` for SQL-Style Joins
- `merge()` is similar to SQL joins.
- Specify `on` or `left_on`/`right_on` to choose key columns.
- Join types: `inner` (default), `left`, `right`, `outer`.

In [19]:
products =pd.concat([df1,df2], axis = 0, ignore_index = False)
products

   ProductID ProductName  Price
0        101         Pen     10
1        102    Notebook     50
2        103      Marker     30
0        104      Pencil      5
1        105      Eraser      8

In [20]:
sales = pd.DataFrame({
    "ProductID":[101,102,104,106],
    "Unitsold": [50,72,48,56]
})

In [21]:
pd.merge(products,sales, on = "ProductID", how = "inner")

   ProductID ProductName  Price  Unitsold
0        101         Pen     10        50
1        102    Notebook     50        72
2        104      Pencil      5        48

In [22]:
pd.merge(products,sales, on = "ProductID", how = "left")

   ProductID ProductName  Price  Unitsold
0        101         Pen     10      50.0
1        102    Notebook     50      72.0
2        103      Marker     30       NaN
3        104      Pencil      5      48.0
4        105      Eraser      8       NaN

In [24]:
pd.merge(products,sales, on = "ProductID", how = "right")

   ProductID ProductName  Price  Unitsold
0        101         Pen   10.0        50
1        102    Notebook   50.0        72
2        104      Pencil    5.0        48
3        106         NaN    NaN        56

In [23]:
pd.merge(products,sales, on = "ProductID", how = "outer")

   ProductID ProductName  Price  Unitsold
0        101         Pen   10.0      50.0
1        102    Notebook   50.0      72.0
2        103      Marker   30.0       NaN
3        104      Pencil    5.0      48.0
4        105      Eraser    8.0       NaN
5        106         NaN    NaN      56.0

## 3. Using `join()` with Index Alignment
- `join()` joins DataFrames on their index or on a key column.
- By default, joins on index; can specify `on='col'`.
- Useful for adding columns to an existing DataFrame.

In [25]:
products =pd.concat([df1,df2], axis = 0, ignore_index = False)
products

   ProductID ProductName  Price
0        101         Pen     10
1        102    Notebook     50
2        103      Marker     30
0        104      Pencil      5
1        105      Eraser      8

In [29]:
sales = pd.DataFrame({
    "stock" : [100, 60,80,120,150],
}, index = [101, 102, 103, 104, 105])

In [30]:
p_dataset = products.set_index("ProductID")

In [32]:
p_dataset.join(sales)

          ProductName  Price  stock
ProductID
101               Pen     10    100
102          Notebook     50     60
103            Marker     30     80
104            Pencil      5    120
105            Eraser      8    150

## 4. Practical Examples
- Combine sales and revenue data to see performance.
- Merge students with marks to link records.
- Practice with realistic datasets to understand alignment and missing data handling.

In [34]:
import pandas as pd

# Sales data
sales = pd.DataFrame({
    "ProductID": [201, 202, 203, 204],
    "UnitsSold": [500, 300, 400, 250]
})

# Revenue data (missing ProductID 204, extra 205)
revenue = pd.DataFrame({
    "ProductID": [201, 202, 203, 205],
    "Revenue": [7500, 4500, 6800, 1200]
})

In [35]:
merge_df = pd.merge(sales, revenue, on = "ProductID", how = "outer")
merge_df

   ProductID  UnitsSold  Revenue
0        201      500.0   7500.0
1        202      300.0   4500.0
2        203      400.0   6800.0
3        204      250.0      NaN
4        205        NaN   1200.0

## Mini Practice
1. Create three DataFrames: Products, Sales, and Revenue.
2. Concatenate them vertically and horizontally.
3. Merge Sales and Revenue using different join types.
4. Join Products with Sales based on index or a key.
5. Analyze missing values after joins.

In [40]:

import pandas as pd

# 1. Create three DataFrames: Products, Sales, and Revenue
products = pd.DataFrame({
    "ProductID": [101, 102, 103, 104],
    "ProductName": ["Pen", "Notebook", "Pencil", "Eraser"]
})

sales = pd.DataFrame({
    "ProductID": [101, 102, 103, 105],
    "UnitsSold": [200, 150, 300, 50]
})

revenue = pd.DataFrame({
    "ProductID": [101, 102, 104, 105],
    "Revenue": [1000, 2500, 800, 200]
})

# 2. Concatenate them vertically and horizontally
print("Concatenate them vertically")
print(pd.concat([products, sales, revenue]))
print("Concatenate them horizontally")
print(pd.concat([products,sales, revenue], axis = 1))

# 3. Merge Sales and Revenue using different join types (inner, left, right, outer)
print("Merge Sales and Revenue using different join types")
print("Inner")
print(pd.merge(sales, revenue, on = "ProductID", how = "inner"))
print("Left")
print(pd.merge(sales, revenue, on = "ProductID", how = "left"))
print("Right")
print(pd.merge(sales, revenue, on = "ProductID", how = "right"))
print("Outer")
print(pd.merge(sales, revenue, on = "ProductID", how = "outer"))

# 4. Join Products with Sales based on index or a key
print("Join Products with Sales based on index or a key")
print(products.set_index("ProductID").join(sales.set_index("ProductID")))

Concatenate them vertically
   ProductID ProductName  UnitsSold  Revenue
0        101         Pen        NaN      NaN
1        102    Notebook        NaN      NaN
2        103      Pencil        NaN      NaN
3        104      Eraser        NaN      NaN
0        101         NaN      200.0      NaN
1        102         NaN      150.0      NaN
2        103         NaN      300.0      NaN
3        105         NaN       50.0      NaN
0        101         NaN        NaN   1000.0
1        102         NaN        NaN   2500.0
2        104         NaN        NaN    800.0
3        105         NaN        NaN    200.0
Concatenate them horizontally
   ProductID ProductName  ProductID  UnitsSold  ProductID  Revenue
0        101         Pen        101        200        101     1000
1        102    Notebook        102        150        102     2500
2        103      Pencil        103        300        104      800
3        104      Eraser        105         50        105      200
Merge Sales and Revenue using different join types
Inner
   ProductID  UnitsSold  Revenue
0        101        200     1000
1        102        150     2500
2        105         50      200
Left
   ProductID  UnitsSold  Revenue
0        101        200   1000.0
1        102        150   2500.0
2        103        300      NaN
3        105         50    200.0
Right
   ProductID  UnitsSold  Revenue
0        101      200.0     1000
1        102      150.0     2500
2        104        NaN      800
3        105       50.0      200
Outer
   ProductID  UnitsSold  Revenue
0        101      200.0   1000.0
1        102      150.0   2500.0
2        103      300.0      NaN
3        104        NaN    800.0
4        105       50.0    200.0
Join Products with Sales based on index or a key
          ProductName  UnitsSold
ProductID
101               Pen      200.0
102          Notebook      150.0
103            Pencil      300.0
104            Eraser        NaN

---
## Summary
- Used `concat()` for stacking data vertically and horizontally.
- Performed SQL-style joins with `merge()`.
- Applied `join()` with index alignment.
- Explored practical use-cases like sales vs revenue, students vs marks.