# 🐼 Pandas - Class 6: GroupBy & Aggregations
Welcome to **Class 6** of our Pandas series. Today we’ll learn how to group data and perform aggregations.

## 1. Concept of Split–Apply–Combine
- **Split** the data into groups based on some criteria.
- **Apply** a function (e.g., sum, mean) to each group.
- **Combine** the results into a new DataFrame or Series.

This is the core idea behind `groupby`.

In [1]:
import pandas as pd

# New dataset: Employees, their Department, and Salary
data = {
    "Employee": ["John", "Sarah", "Mike", "Anna", "Tom", "Laura", "Steve", "Kate"],
    "Department": ["HR", "IT", "IT", "Finance", "Finance", "HR", "IT", "Finance"],
    "Salary": [50000, 70000, 72000, 65000, 60000, 52000, 75000, 58000]
}

df = pd.DataFrame(data)

In [2]:
df

  Employee Department  Salary
0     John         HR   50000
1    Sarah         IT   70000
2     Mike         IT   72000
3     Anna    Finance   65000
4      Tom    Finance   60000
5    Laura         HR   52000
6    Steve         IT   75000
7     Kate    Finance   58000

In [3]:
df[df["Department"] == 'IT']['Salary'].mean() #this provife the mean of one department salary

np.float64(72333.33333333333)

In [4]:
df.groupby('Department')['Salary'].mean() # this provide the mean of multiple department salary

Department
Finance    61000.000000
HR         51000.000000
IT         72333.333333
Name: Salary, dtype: float64

In [5]:
df.groupby('Department').value_counts()

Department  Employee  Salary
Finance     Anna      65000     1
            Kate      58000     1
            Tom       60000     1
HR          John      50000     1
            Laura     52000     1
IT          Mike      72000     1
            Sarah     70000     1
            Steve     75000     1
Name: count, dtype: int64

## 2. Using `groupby()` with Aggregation Functions
- Use `groupby('col').mean()` or other functions like sum, count, min, max.
- You can also use `agg()` to pass multiple functions at once.

In [6]:
df.groupby('Department')['Salary'].agg(['mean', 'max', 'min'])

                    mean    max    min
Department
Finance     61000.000000  65000  58000
HR          51000.000000  52000  50000
IT          72333.333333  75000  70000

## 3. Multiple Aggregations on Different Columns
- With `agg()`, you can specify different functions for each column.
- Example: `df.groupby('Dept').agg({'Salary':'mean', 'Age':'max'})`.

In [7]:
data = {
    "Employee": ["John", "Sarah", "Mike", "Anna", "Tom", "Laura", "Steve", "Kate"],
    "Department": ["HR", "IT", "IT", "Finance", "Finance", "HR", "IT", "Finance"],
    "Salary": [50000, 70000, 72000, 65000, 60000, 52000, 75000, 58000],
    "Age": [28, 32, 30, 27, 35, 29, 31, 26]
}
df = pd.DataFrame(data)
df

  Employee Department  Salary  Age
0     John         HR   50000   28
1    Sarah         IT   70000   32
2     Mike         IT   72000   30
3     Anna    Finance   65000   27
4      Tom    Finance   60000   35
5    Laura         HR   52000   29
6    Steve         IT   75000   31
7     Kate    Finance   58000   26

In [8]:
df.groupby('Department').agg({
    'Salary':['mean', 'max', 'min'],
    'Age':['max', 'min', 'mean']
})

                  Salary               Age
                    mean    max    min max min       mean
Department
Finance     61000.000000  65000  58000  35  26  29.333333
HR          51000.000000  52000  50000  29  28  28.500000
IT          72333.333333  75000  70000  32  30  31.000000

## 4. Pivot Tables & Crosstab
- `pivot_table()` summarizes data like Excel pivot tables.
- `crosstab()` shows frequency counts of combinations of factors.
- Both are powerful for summarizing and comparing groups.

In [10]:
df.pivot_table(index='Department', values=['Salary', 'Age'], aggfunc='mean')

                  Age        Salary
Department
Finance     29.333333  61000.000000
HR          28.500000  51000.000000
IT          31.000000  72333.333333

In [11]:
df['AgeGruop'] = pd.cut(df['Age'], bins = [25,30,35,40], labels = ['25-30', '30-35', '35-40'])
df

  Employee Department  Salary  Age AgeGruop
0     John         HR   50000   28    25-30
1    Sarah         IT   70000   32    30-35
2     Mike         IT   72000   30    25-30
3     Anna    Finance   65000   27    25-30
4      Tom    Finance   60000   35    30-35
5    Laura         HR   52000   29    25-30
6    Steve         IT   75000   31    30-35
7     Kate    Finance   58000   26    25-30

In [12]:
pd.crosstab(df['Department'], df['AgeGruop'])

AgeGruop    25-30  30-35
Department
Finance         2      1
HR              2      0
IT              1      2

## Mini Practice
1. Create a DataFrame with columns: Department, Employee, Salary, Age, City.
2. Group by Department to get average Salary and max Age.
3. Apply multiple aggregations using agg().
4. Create a pivot_table to see mean Salary by Department and City.
5. Build a crosstab for Department vs City.

In [23]:

# 1. Create a DataFrame with columns: Department, Employee, Salary, Age, City
data = {
    "Department": ["HR", "IT", "IT", "Finance", "Finance", "HR", "IT", "Finance"],
    "Employee": ["John", "Sarah", "Mike", "Anna", "Tom", "Laura", "Steve", "Kate"],
    "Salary": [50000, 70000, 72000, 6500, 60000, 52000, 75000, 58000],
    "Age": [28, 32, 30, 27, 35, 29, 31, 26],
    "City": ["New York", "Los Angeles", "Chicago", "New York", "Chicago", "Los Angeles", "Chicago", "Los Angeles"]
}
df = pd.DataFrame(data)
df

# 2. Group by Department to get average Salary and max Age

print(df.groupby("Department")['Salary'].mean())

# 3. Apply multiple aggregations using agg()
# Example: mean Salary, max Age per Department
print("3. Apply multiple aggregations using agg()")
print(df.groupby('Department').agg({
    'Salary':['mean'],
    'Age':['max']
}))

# 4. Create a pivot_table to see mean Salary by Department and City
print("4. Create a pivot_table to see mean Salary by Department and City")

print(df.pivot_table(values = 'Salary', index = 'Department', columns = 'City'))

# 5. Build a crosstab for Department vs City
print("5. Build a crosstab for Department vs City")
print(pd.crosstab(df['Department'], df['City']))

Department
Finance    41500.000000
HR         51000.000000
IT         72333.333333
Name: Salary, dtype: float64
3. Apply multiple aggregations using agg()
                  Salary Age
                    mean max
Department
Finance     41500.000000  35
HR          51000.000000  29
IT          72333.333333  32
4. Create a pivot_table to see mean Salary by Department and City
City        Chicago  Los Angeles  New York
Department
Finance     60000.0      58000.0    6500.0
HR              NaN      52000.0   50000.0
IT          73500.0      70000.0       NaN
5. Build a crosstab for Department vs City
City        Chicago  Los Angeles  New York
Department
Finance           1            1         1
HR                0            1         1
IT                2            1         0

---
## Summary
- Learned the split–apply–combine concept.
- Used `groupby()` with aggregation functions.
- Applied multiple aggregations to different columns.
- Explored `pivot_table` and `crosstab` for summarizing data.